---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mattermost-operator
  namespace: mattermost
spec:
  chart:
    spec:
      chart: mattermost-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mattermost
      version: "1.0.3"
  interval: 1h
