---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    apiToken: AgB8DWFtzhjhTPigrbtskDrYSAMktfzQHioDFtz29tuzafoKHfk0MAtFnYaDyr9HlaSrhtwNPqkn0TzBYJcCXQa6bPeGylX92bkkWNXWLCWxAbv5hX6b+RcKqUdn++57VY+zvkV6eb9y2Pso4iYyrKp4DKmKtPaduU3MVSG1as0rO2LFDA1aQ2lYwqaYVCV2JSEzg3JRPHJxCqgG8lHgwdk5LQ0NtyOpQ6yBY9yuISYM/gGrPfeZ6aPb1TlveMk4ELt7DN3t4dBTwwzK/llmcUKlf7bn3/46GIadU6zEAWhxpe3ML9bC5HoaxHB2P8qbNARD0mLijdm9G+zAUMzS+C9ACBNGeWISvVxn8Zv4jMIAzU5B1utqzWLmrlDpWQPo6IQhTTyig/k9qP0mk3gb1kthxprKbIz5anC79FqhUQLj6bO1HX2xO7W47ITXGEP9X0q8Hz9x17BarjJcEyT9j2yLD3ZnkZYsAbk/PCSCbXBFHHouzI6xjut+Bnv4GF56IFiZ19ez4V0fxZbr8bMTNgLMRAwwBjshHyBQCgeB65yY2T8knrQSJDuvIlmfxfdlyKCz6ZyWUOiZ6UdtmisiAjYhb6GaHxo+NDKm1sYYmUtj6Noq4ifJ7PX3rp1/lFPAm3UsinRYMumuTyZ20MuCbgic0Z/BMeuAlKBcgRabxUg8LQ0I2r+Co/3YOiIHCf5ue37KqNq9nua6jdzvUPen/L2AD/T0OtLIaBctnl948Qvtq8QWQmma3LI/
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
