---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    apiToken: AgBlDo4BmPC8xr3T7YKfPbHjhH/eexeagkOI1wqVu1uRAfmUOdmaWU566ShUNch/c/s4sWcYiuupHgrq4Y8PDDLz+K1e+R8dar+b2XY+NJhTas6ddI1wbFJ1dkP9B0RmgA7wRTcz6fjRs1n7pONZKxx1Er9KNyXj/gQ0cL19MQO7cgxGcDA28eow8ol73IzxymbUxo43siTqaaf9KWScKGMXKrJbQ16hEEZyUuoZkzPN7VXpmCYRmkmVUKYBYDyW5yAu/lwhOzbemHwqLLok31UENY+G1C+a+6uIbWIMdDW2FMUUB0uNu8YTNLbLDG6HJQSi+0mbvKAgrxPBsCJUa8JAA4W8dsYYrh4886p4EH0ooegJbIFztBfGxfiPXPuFrVV1IhJxrqY3iWk2olXa/3PKLCZHJwhUoAlI2W3bKsZStXcrXhMIFEt9ErO4bKiTdv/CjbiVt9MBhjTYCGMK9rGD4qmoVvUINOlKEJI4fyJoM76+vxlf2ibQQ2kpRdhborSmdcw2wKmPXZpVYM8M3k3KEze2OBuG8whtdak8UVnP9qRrEpZSzRNd87YyjEh+/VU7BOk+bSaO5CVk4mpk1moJGq/os5bcAarDhnG/2k131JFHmZyjn7pmYDUDHoqyrVavF+EK7qOSII4+Y44LC5inVgzelhWGj5bXWw1GOIUPoTSmeIrZmQ/L3lmnNIpLcFnmnMyGvkAMtBfp7jE5hid+SGcqJ2mNtZDfjVti88sE1qO238lMNZFA
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
