apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-certificate
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: home-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.home.lorenzolab.com"
