apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glance-certificate
  namespace: glance
spec:
  # Secret names are always required.
  secretName: glance-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - home.lorenzolab.com
