apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-cache
  namespace: opencloud
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  storageClassName: cephfs
