---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    apiToken: AgCoue/GcUgzsIy/SLjHtAmv77InFFwULcUWw8cWJ0AWM2iBJ0FpY5ub382rkLo8F+hJ50pdAivhA3qCMsyt13y6nw84jHfvkH/WG0ueN5wdX4Z/1acL5vuEt/emp4/txximcTtrUwrTzBEi6PXTitUpa0xSVfT0K/3lBnJ5fFfqyrGWo33dNRw7xGHaO8GjZQAo57XEFb5Tp08DuEEPXL32ZjRoTw297rAHFwoj+k9h8AEPmzNnEXgKeamQspAPvOv/CjG5I4ZoLhf9dvB9opsXj7NE9pI1Qpax2N8wLZ7WfFTSiRrFEh10C1nQVvATsCnzFlvCJpZa9KK9Q/W/ysevAl7OjxNSdUi3w/JFr/yArb15f7C3IIbhTmwX9la3HQ59aMFLprTnt5tEfUgSk0oCo5kH7B/uQryZ945Z1Fa8dYq+sDNhOWU72w2DagFh6uHr9t/wMgmUypJ/jDxQXZQOCgkf9sBkNXHuXEbWKKIzm6jIGgRaby64awTwB0wDNcbGhzptwIFyfHZ+NcRKlIJ2rjBlGxRnNlFrwEGc3RkSHsNC86QDqf/840HlfK8PbegymoHbTCiiGmmuQ32xoYS+vzQLDWn9QUOXTyfq7XByksmdrdsYlQ2wOztZiXlAG3nxc/eQHm1Gr0Saj/nB2WsG44Jt9+N97A16oLVe2ruvZd7VBCw6MSYqfJJU9xumxwXeksWx/U7WrCxpISemQEb8CHsPCxg8h/Vksae/jZOMyQitXNmZBxEu
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
