apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
stringData:
  userID: ENC[AES256_GCM,data:EijT,iv:IQvN+JPl/S4ecK7QAGS1BudX6xFfo8C0eBawjSM5bG0=,tag:ffdy55wK1ySHPhWbDQLeAg==,type:str]
  userKey: ENC[AES256_GCM,data:GP+BSemR2r/BbHw03dLd3F4L/j9Do0xZkxvaBv4pY+eyps7nc6/opw==,iv:WNTMVARdDvBOwFACGlcKBHC1NzYAWcgnnOfs8Hgbxmc=,tag:YVdnb4gEr/95DPJ4mq6vDg==,type:str]
sops:
  age:
    - recipient: age1dkx5fryjw78lpvu4fkk59k4ljl24a5cnsd5nj5sefh05p3xn9anszpqxuq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUkVsTWVENzdxVlJJdklQ
        OVNIQWpkbmttSFhtUjZxazNNU2xEMUlJdm5JCi9pWnFwMVZMS2JZQi90ekdYc0FF
        Y0xoeW9Hby9WZ3dKcVkyMzV2b1Rnbm8KLS0tIGRaWi9YSDVhc2xINmdKeWRxREUr
        VGlZYjRiZVZ2c3ZBTDRucmcrNXBzKzQK9yxrMHML65z6B9nqtWsINL1k1Sx4/g4S
        0vxZVfB4K4cPmLhO5Em0/CWrEclXIl+oN4GqlI/kkaJMrI4v//j3Jg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-24T16:28:58Z"
  mac: ENC[AES256_GCM,data:Qx4KNEMz+HL4Fpe99KFOqtzlT4jZVIHyK4A7N2XsnZoQ2gm0f98f1C7aeB7NpF4ElTc9fpkZyAlsyYDkCQXhan39MApz4octmSVTvVFtkghS5U1eihojGdsYxRabhMNrDrsLhPInDzXiCNap/tQeuCFop9qWKRnmA3m//UVdZ1Y=,iv:v2egGFkamHmWfzwk0uS90fYQiUAhX7TZa+yXGqbQXB4=,tag:XvdJXwy1NE8klakMGI3u6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
