---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "1a63ec44-ead9-4c25-9596-145909fad31d",
        "monitors": [
          "10.0.2.1:6789",
          "10.0.2.2:6789",
          "10.0.2.3:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
