---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattermost
resources:
  - ./mattermost-db-secret.yaml
  - ./mattermost-filestore-secret.yaml
  - ./mattermost-certificate.yaml
  - ./installation.yaml
