apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mattermost-certificate
  namespace: mattermost
spec:
  # Secret names are always required.
  secretName: mattermost-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - mattermost.lorenzolab.com
