apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbox-certificate
  namespace: netbox
spec:
  # Secret names are always required.
  secretName: netbox-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - netbox.home.lorenzolab.com
