---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbox-repo
  namespace: netbox
spec:
  interval: 1h
  url: https://charts.netbox.oss.netboxlabs.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  chart:
    spec:
      chart: netbox
      sourceRef:
        kind: HelmRepository
        name: netbox-repo
      version: "5.0.71"
  interval: 1h
  timeout: 10m
  test:
    enable: true
  values:
    cors:
      originAllowAll: true
    postgresql:
      enabled: false
    externalDatabase:
      host: db-1.cluster.lorenzolab.com
      database: netbox
      username: netbox
      existingSecretName: netbox-secret
      existingSecretKey: dbPassword
    redis:
      enabled: false
    tasksRedis:
      host: redis-1.cluster.lorenzolab.com
    cachingRedis:
      host: redis-1.cluster.lorenzolab.com
    ingress:
      enabled: true
      hosts:
        - host: netbox.home.lorenzolab.com
          paths:
            - /
      tls:
        - hosts:
            - netbox.home.lorenzolab.com
          secretName: home-certificate-secret
