apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-certificate
  namespace: db
spec:
  # Secret names are always required.
  secretName: pgadmin-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - pgadmin.home.lorenzolab.com
