---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbox-secret
  namespace: netbox
spec:
  encryptedData:
    dbPassword: AgB+C2jdJl5F56CIqjWBOUB+/SmuvMtBZapKivgTHHXGg+RCu0Yf50dLGj+fxJmhGVVMun3W2iUlhr1seA2Zyn1iWnZ78gEo54SEYMfPJJIVKZCCJKS+o8tcpKLof1rFyhC1xDE/IfLNLrdo7WGSJbu/aO643Xiu+PNWQpgR5Y735Q+vr17gacggL3WA6yoNpkDCf1ghXVZP46RP9Fa2Tw4t2KnbAFZrX8FzywtsJez8Kmm5XMnxc1jU/4SDYoeHJCtmjsk0gjabZPJ6rjGp7KG6S0eYZznOH6ycdW5uggMo9xoNO8FxMGvJZKTMcM9n/gzt6Q8PqYJLhwZbcM7VrTaf/VfKr7l9Th/jWA1mkcYWw+MA8AyFMbul8eS9pvfjOQR9HXGaoXcQGv0niqnQiY+frbvWbr0Z3upC4venOOHmcAoG3ZmflWwC6CPlOo9QZANJ8dKENnUjt5+azQ3+MX9Ooc6PSg4xZbQqw0PF9ElcAClgSyG+Yua6nDVEZwO0VG2An1I78zioJ8AOMWRNPfCw/iejPvZz0Zcea9XnUFNdPn5IeHVFLzc1guoOG9JuVWRdRS1Rr2Fs4SN1VUjk5azbZzbQfYmcG2r0UFFP8LMMn2A2heWk3OEj1MvHVd9Of2IQtpS5G1wqToteBmnarb/AutjKnPGpblEQ74VZC1+Y9kYx8pIkbVSKP3LlGamM4OhZqBBO5pFAaDIU7NZ325qDt8mc
    redisPassword: AgCL43EembIZiUB2K08kvVW0xV1AQucCQSVS66Z2JksNealywnsv4qyJ6JIb8iBuigFDDEwiR5o+G/m07zbjgtrehgbUXwixFh6dBUyn5FFannLIvvcC6lhGQ6LRworoqxlrOZu5adB5QuDF+/1ZWfQh6PDSbG3JL9jWt46mF8G90cT4N52IXNNjb3XbMQrshjQKMng6UlYVaG4e5sf4jpIPLz8HnE3QsGRDJtBQ4YQx0+egbw8zjVQngdhwpwcYkxBzQ+1VbqcyByX0rMIrUjJIR/YJDvvxlC2M15wQWd9Mn3jTlDzgU4nLjuGfomtccCuNLeM188/wMVHCkWxa0yayyFZRfqCsmBx63J00jhMBkRMvfYBF+5LKieec3IuRfrRbViA0yyZFbIvqq8DbB+UwJ8Kb0qeHTXa+zBgHwCcDbmRW+JahI4wfgRG6tjXBwze6DfDR7eLA4QgRnmii9whXZy9gtfRi8qQhdaaSp2aE/wlDDs1GpZ/yuhmSsf4FtPX254i9zHPNw41eB+rXupmrTPf/fTTqFaWV+g5fhGnl+MBGCdWKvN0Nop1NmUOYMOrAsRcofaSNvX3xSc5ousYCrPnYelllitObRH5+Ce3AppntQ4mJmjac8hFvP8UyM4d/5Nd5241ztFGoVg0HbF9JjWi9h6/M3hBq6vrHN00LKSYz810KiPYRzEA6GnVW3ttaPbQrdi2m3jMb6JWLYHWW
  template:
    metadata:
      creationTimestamp: null
      name: netbox-secret
      namespace: netbox
