---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBhvFCTjpFfiaAYSXEzf0JbUFvBLBaEXZ7XkYcpNE9MFC11REmrfR1hjIXJb9B8Yb20QYXDVpNMSEj50tQ8Yc5eKv+nIAwkaVlWUlb/6k0LmkD4Nw8WGUZzh8ZEHRH4G/Qt2U/9JnxZYhWYPwQT1sDXOYQgXUkhMqRcdmo5hHnWTuYsp7qTNRA/JV9+7z5dnUOgV9aLi7RTwNfd1/vMkdpCzWZ0PBibpVrmMpoaIFRiarlVkAbVXnKA1CNgGCQTYZvTPfe+3L+gN1LvcnvKxcdJfC14jNwzg7LbVUmOyqgAvIZQ6iVrOU2iCrm6P8+Bi/4lSdmM1hte5OSJ9ANV8HccohItnu7dD48Vfq/69a3aZKvc9iP4SC+0B5thQc5Ur+gKOhZ+qgM92UWIyZjd3QL5bypVh4onPr8LclQPnu+w8hNnNELSO8h6D3F2+7bYitgOb/VVM+Aly6yCitpBfoPth0ek4yc3kswQVT0k1cO6A6AvAbM2R0Hmmx4F5nH6XKHKaqopVXe6diK3ILDzFt01HxTWQNizLWEeeEo2alHgRetiE7h5CWKBBRx9TJa3Ni3Ah/1I4cVZjkUoIgKVdHCVObCKTy0C6K//Zcl+pp2ruYt0i/VPj3cO5iEM+0GbQRw9Ke5nVpEkYv62gttHMSSoMhTObs97Gv9cAXSZgIct0t0Xrx/KM7lA+qaO7pAlisyvV5iLEzMAUkuJzBs=
    admin-user: AgABC4FrmwUC3MOg18+tkvy58ZjwPo70pRLsAElnykQudHRPVgNYdzGOiN4xrz3ZP9GibjaQGEBXmar29LWFktZ76Oo19NIxczEMY2LMt19VfwdJv7mecuXZhjb+hXNTjL2ud5Beo0IK3gG0rP+ob2iSJbskIq1HvkW0CzROwtqyxTON6kF2vMSkWYok/Rz14ruRgZcJS0y0WPb+a0sfl8Pug/Ma89voGxk9zTjKBJB+vjqmz7csyJBICKpRCoaWzOqlr7L8ddVm8On8KuPOL9IYjOYC8bJs+tNOu7c91iaoSSJ3L89PY/B5KzqeYFdkv5liVVQ/1lhrkyQSRunawV+pUySmmY9auUJGRos8YG3JXc/kU8tCgq5aeq+xshT6AlLxOZ/5pGiVGzrbUvo0l2a8isxCd1wUOAzQGle7qIydZ/i9FItwIRyYi+exM5Ns7gttEWuShyWutf4s8Gu0CM5cq2nd4MPrwYIvdm1k7CtyAMjlX+xMN3YctlB8qUVWzYNu0bVdIQrajuTYw+1NMb+nskxCu1ZTN+mUg7GeUS7pbaheoAzqiS0BQnwUTOa9Y6XxsPNb/1v+QRLVscPqOjUVanim5tIrRr3TgNmljLFERchY9/wgAuEMroITmVduP/MHwLsBLwDttFuYSEwxGfrHr5QKN6u45zE/Vry5WJUkg4Vki4iY77WE4/ocdQZ2iBsTNhds74mc
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
