apiVersion: v1
data:
    client_id: ENC[AES256_GCM,data:Q+6uBmAax71jcn+LpAyNCMoO4i3E/ZTetHg2WpzPLvyWZaW4vgPaJ2O1ITkIXK24hpk/nBAg6pI=,iv:+dIsnJSeUgLOIpI/YzaehAkSRijICbz8R4TH8Ju0Obg=,tag:lnfPWQU3OnDQxiQx6DmiKQ==,type:str]
    client_secret: ENC[AES256_GCM,data:ehCNJvL4086kUsHxIQkHHD61dRYL3SPo2cXm9favbzSngJ0ao4wi9Qhbjcw0C/SyUJlL1CbxljlwbYrxkJshCpo5yPLdPCfkWVd/gKW8xEZFU4sEmPnj8xyF2qEl27ALP2JoTgaqO9Tpe4rleZzeQI+gTDAXlP8XhvR9uU0YLUfjCp1yubM0gYo9mazDJPaYO09jZeVaSVCS3XhXjirP+69YZPTUO1rpL7QgLw==,iv:YY5Ed7tOrB3d9rvrMnF2vtrbXLBtuAd9YbTRgMXeip4=,tag:gJiTDof9BFzUA2NuxuYJ5g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-oauth-secret
    namespace: observability
sops:
    age:
        - recipient: age1dkx5fryjw78lpvu4fkk59k4ljl24a5cnsd5nj5sefh05p3xn9anszpqxuq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTTIzbHpET3BadjRPZFNV
            NG5vaWlQWFVOcitpYVMvSGFISGdtLy9CTDJ3CjFpcXUyS0ZIcFB2dzl2TU1xQVVY
            OGtRZ1c4YmY0SndYeUw5Nmt4VWdBYWMKLS0tIGx5K1pJTllMOU8zaEVOUzRVNHBU
            aHBxVklBbHpnWDZ0SmVPaEZxa0QwR1UKf2ZpKvY3D3dyVCY8C2y0YFt/0gP17N7o
            KEUjKMj8nxMJVE5WEGIIqWb7IHZvvO72NhfolPwSwr4de4XM4+an0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T20:19:48Z"
    mac: ENC[AES256_GCM,data:23ZZIRPWPK62UxVa1jSoGlpqEj72bb8bzun3g/dJDrJkIdzxZkXfFbbtteAvMJ63jTTHKHNZtGSqfRy66IdIqSACbwLhINA396jWYkhTQMvVxdhqzttbCNjTTtwNUSDos1qCTQ0arLlLJvxEO6cXjEb5ie3NkGAvXj1IWaetg+Y=,iv:+/h3l1sHfCPdnm6Njc3Mbqpi3gl2s+NBOHwggRrrsZA=,tag:6MJY0py82Ob1nJvefOF+Pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
