apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: ceph-rbd
