---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actual-repo
  namespace: actual
spec:
  interval: 1h
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
  namespace: actual
spec:
  chart:
    spec:
      chart: actualbudget
      sourceRef:
        kind: HelmRepository
        name: actual-repo
      version: "1.5.2"
  interval: 1h
  values:
    files:
      server: /data/server-files
      user: /data/user-files
    ingress:
      enabled: true
      hosts:
        - host: actual.lorenzolab.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - actual.lorenzolab.com
          secretName: actual-certificate-secret
    persistence:
      enabled: true
      existingClaim: actualbudget-volume
      accessModes:
        - ReadWriteMany
