apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: actual-certificate
  namespace: actual
spec:
  # Secret names are always required.
  secretName: actual-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - actual.home.lorenzolab.com
