apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - openid-secret.yaml
  - actual-certificate.yaml
  - actual-pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
