---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-email-credentials
  namespace: auth
spec:
  encryptedData:
    password: AgBIxQgQHk9H/hxWnNV6mpNAFEQKck366pc1pl9gEpAIcudi7j5rAcmMms8r0dHhPZH+V4n9litkOTbUBIn5Q/xys/W+BuRYINyxmVvjP6cvHm3dT8wnFOUOjlHOaSTkrnLgPo3y//0CeBZBGdVgZ+MDjjGJwODhoNSMUfoqbJ+0XhCakUCw+XuMrXiG4DYUhB2KdQsluRqaCk0sc6ikQ0PNuJDpnGGWxJ7T0GLq+rz/rnNIjbsluL9jZw+wB2t1RPgxE5nUg5mqyrNcqXau6VB944LekzMtAtGFiwfwyWeOSOICCU7fHa5KVW/IivWiMNjSEV8WS9korI5kzkLwIACfg+jOjGK8OvJsLrDNQAJ57V1gSCASwk4k//6pooYJgnOHodEtgI/uSKVzgc9vAxuSPlNAiZi4Pf+vQl7pZxsYRysFsAsQsg805Tr7qpfFYoog3a0WiAdefpa2bLx6fKuxP42/BB35d4kFJ4/TRu78iG3nAhzkM65YnLy0C5XMP8Usd8CU9kswOFuxQNZgjegm3W8iL9GX/IPHDrm8YCJ+zjkuVTwTNdw8RmgWInSQQHscjN/wltSyKcXDIuDWusRfll0J0NWCHK7Dbc7Z35eSxuU+RWlZqk024RDhj/oERcznFSb4QvCySMcKl+9uiIYSy+I13dh64pvv9YiTXSmu75F7nEykGHXeX0+0Wsk0QH8qochJaH2yja0wT9cNxNnOPcuqh/rEq/qP95rT/9MCgxmwdLg=
    username: AgCjXrl8f/3axwIZC/osb/rEzAtQAnnXmWIpzfHBiEFAY/P74DYJZ7VTJZmdc0SD/0NOfRph0wexBLL2zZoEC+RhQ4F9m+tSV02+H7/SX6bNarUxqAFLBvAGd7hnz0avydoA+T8CJCwOO3/TX5+xW7y2+6Rg9dNN0HYkQkkTwfOd0o84bTzO3QrJZ2nYLrbJlzjJHI3w7E9qZ854Kt6uY6hLq8xMGHi8OAqI8oXE5uaVYty7NYfaRpvfSEIqBhckF8g5vE9rJpazqwBDE7sU2IMc38XQEaLCLG4jmkqllxPzflSKnrbFVOamnT2surZVS9NMKU4kac+emiLghJy3bbPAO79LviTaS1BcJLluhSYks1VpWj597nP8vOqpELLbwe6mFbWOX4jbm4BQQP2vq5ZDkJso3Hj+u+/eW2f7m1eJTX+QAPo9CFTfRKUXKI7ezAnZGW207KXHvwrNd6iH8Ae5CkDX7PYPaoxhEY8ZZf4bqKn9xPluk8cBhooP3IZo8nGIA9i7j8h7HhJBJnL1GX5cJS9T4btxpqhHOcOE/YnTK74bSQlClOFh/NzJBAyZhhtrA95Obj++QA2bfoq8sk08Es2zv0SW3Wh0NMH/krPQII4cR6mHXXVzJ6NHBs2ieIHFOaNeqzlzwGFjOyCkbGpGHrnv6rpe2TzNhsIJGxjYwuexruCNRnHb2y70oBc7bS2eV/HXozc=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-email-credentials
      namespace: auth
