apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - outpost-certificate.yaml
  - authentik-middleware.yaml
  - db-credentials.yaml
  - email-credentials.yaml
  - secret-key.yaml
  - chart-repo.yaml
  - chart-release.yaml
