apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-alerts
  namespace: flux-system
spec:
  providerRef:
    name: mattermost
  eventMetadata:
    summary: flux-system impacted
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
