apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-alerts
  namespace: alerting
spec:
  providerRef:
    name: mattermost
  eventMetadata:
    summary: flux-system impacted
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      name: "*"
      namespace: flux-system
    - kind: HelmRepository
      name: "*"
      namespace: flux-system
    - kind: GitRepository
      name: "*"
      namespace: flux-system
    - kind: Kustomization
      name: "*"
      namespace: flux-system
