apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - target:
      kind: Kustomization
      name: flux-system
    patch: |-
      op: add
      path: /spec/dependsOn/0/name
      value: sealed-secrets
  - target:
      kind: Kustomization
      name: flux-system
    patch: |-
      op: add
      path: /spec/dependsOn/1/name
      value: cert-manager
