apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesGateway:
        enabled: true
    gateway:
      namespacePolicy: All
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.home.lorenzolab.com`)
        entryPoints:
          - web
          - websecure
        tls:
          secretName: traefik-dashboard-certificate-secret
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
