apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secrets
  namespace: cert-manager
spec:
  encryptedData:
    apiToken: AgB3XrgzDO+gY+ftqiclVMdFMfotuBDH9dHV6+xYHcfp3rYugFL67a8DxknXmoGtgpZ53amD4xZssDoiQugMpIh3o2apaAhf+TXxq/YwnlIIwHrHfNp+h+wbOGNoZQ79vooRF3RIi158SoXIgpyycHdcS4XwmaXsWeZodGIthuZ8QHBh0jy4Kv/CHfPhsGNYZSQ739clWmdZld9u/ChkKNcYZoK/ENNZoj8ZP3DvUFX7saCCKpdbrQC7EvfaWEl5yoNsKJBe3ducZIeSio/gfcygx2CSDcvY+1hX4rS6Bof9rlJUEWx2kbBH3FhslekGMM19b8XBmMvVQ0a023hOrCHmq2mBhnbPOLAICOskqHxYDliTlp0Yu29etn+iz63m1m0gQH7MLoYGM2k1lU615eMfjuKm+10btirL7/v2uxNoRcn48j5s2MJo5y7FImsJ1a6HMeLh6yMvOxv+qxGGk3rUEnk3EVBrWeI8RvrrkmX8qB3yOWoy67orNg+GiwNHDmH7zfF2UTyQbrMFy2F95C+99pZ1mnRa7WoNGnP7ZMaiov76pqIhoeM86bldGnzNDhxON0cJp8VLkec+w4T5Pe33Xpnu/B+VUQj2f5Vbb1D8csyCFYVkd/bod+yZYxXPUFQoa9HZVz2QB3SJRYlmiphZNY7B578nS7cIQouGlZMKIQyFGGmOD092SM3jAwnUvXiueUM02V3QL2+eq0PEiYN9+e3KNfvU+rGjDVLUbBF1ihmqPVfoZu87
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secrets
      namespace: cert-manager
    type: Opaque
