---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn
  namespace: &namespace longhorn-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/cluster/longhorn-system/longhorn/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  targetNamespace: *namespace
  timeout: 15m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
    - apiVersion: apps/v1
      kind: Deployment
      name: longhorn-driver-deployer
      namespace: longhorn-system
    - apiVersion: apps/v1
      kind: Deployment
      name: csi-snapshotter
      namespace: longhorn-system
    - apiVersion: apps/v1
      kind: Deployment
      name: csi-resizer
      namespace: longhorn-system
    - apiVersion: apps/v1
      kind: Deployment
      name: csi-provisioner
      namespace: longhorn-system
    - apiVersion: apps/v1
      kind: Deployment
      name: csi-attacher
      namespace: longhorn-system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: longhorn-csi-plugin
      namespace: longhorn-system
