---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ceph
  namespace: &namespace ceph
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/ceph/ceph/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 1h
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: csi-rbdplugin-provisioner
      namespace: *namespace
    - apiVersion: apps/v1
      kind: Deployment
      name: csi-cephfsplugin-provisioner
      namespace: *namespace
    - apiVersion: apps/v1
      kind: DaemonSet
      name: csi-rbdplugin
      namespace: *namespace
    - apiVersion: apps/v1
      kind: DaemonSet
      name: csi-cephfsplugin
      namespace: *namespace
