---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  chart:
    spec:
      chart: netbox
      sourceRef:
        kind: HelmRepository
        name: netbox
      version: "6.0.47"
  interval: 1h
  values:
    cors:
      originAllowAll: true
    postgresql:
      enabled: false
    externalDatabase:
      host: db-1.cluster.lorenzolab.com
      database: netbox
      username: netbox
      existingSecretName: netbox-secret
      existingSecretKey: dbPassword
    valkey:
      enabled: false
    tasksDatabase:
      host: redis-1.cluster.lorenzolab.com
    cachingDatabase:
      host: redis-1.cluster.lorenzolab.com
    persistence:
      existingClaim: netbox
      accessMode: ReadWriteMany
    ingress:
      enabled: true
      hosts:
        - host: netbox.home.lorenzolab.com
          paths:
            - /
      tls:
        - hosts:
            - netbox.home.lorenzolab.com
          secretName: netbox-certificate-secret
