---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbox-repo
  namespace: netbox
spec:
  interval: 1h
  url: https://charts.netbox.oss.netboxlabs.com/
