apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media
  namespace: netbox
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
