apiVersion: v1
kind: Secret
metadata:
  name: gitea-cache-credentials
  namespace: git
stringData:
  cache: ENC[AES256_GCM,data:BuYgp906urYu59PdLWN0d39H7RO80J8EYmBTI2NPnNMsEftwLvcGQeycSMKq1fthoC0t6yMuxdH8BEhOstTh81U=,iv:cN1Q1u1N0O6ISJblJ8hJfR1cPZ5SMe9WpFojTinxVhs=,tag:lpBLBcw13O9q8eFUKK2/qg==,type:str]
sops:
  age:
    - recipient: age1dkx5fryjw78lpvu4fkk59k4ljl24a5cnsd5nj5sefh05p3xn9anszpqxuq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQnhuNmQ4WHB2WERlK1pN
        U3JBUFptOERGUk9ycEJ3M2FueVpkdmxCb2dzCmJCbXNtcWFSc29iaU1Xa2FlQllX
        TmxKVCtpcUFYZmZ2YlNsWnZvTjBRczQKLS0tIEZ6a2EwUVV3bHBOK1h3UXhGS05k
        N2ExSUcwcHhGUEVVZTFSNUp6R2tlSGsKdtr5BHx77Vn9IoiWXAYtboXRX4YLrfnZ
        VnXebOf7QuWdIeZ7OfQcSSVn8ay7oB3LBKbZ1iU7in9cjUY7dGt6Nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-07T21:09:57Z"
  mac: ENC[AES256_GCM,data:OB+gaYQvl5vDGM0X2I7kweNPMR8RoVhBxF2gR/7UXMFUAbLQp3v33rKSLSN2Vz9HhOgovf4h2I5Dga4D0p5QKqBZrxc5dZRmXKBp7BdZi4bW7RaidwJQDe0zgd/tUsbIr+UcwY9seAmtSidB0XyaqGrKdARLSFj46ygfg2Ow4JU=,iv:z2BwP47gd0jB8zvwZgFJd8AtQBn6jq6MJHJXtqQfTmY=,tag:ph+leIiDztNyS7ZKyLJC+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
