apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-certificate
  namespace: git
spec:
  # Secret names are always required.
  secretName: git-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - git.lorenzolab.com
