apiVersion: v1
kind: Secret
metadata:
  name: gitea-mailer-credentials
  namespace: git
stringData:
  mailer: |
    ENABLED=true
    PROTOCOL=smtps
    SMTP_ADDR=smtp.resend.com
    SMTP_PORT=2465
    USER=resend
    PASSWD=re_Ywx6JQaH_3VHDSQRQ6SBvGgTM6puBkNWr
    FROM=gitea@transactional.lorenzolab.com
    FROM_DISPLAY_NAME_FORMAT=Gitea
