---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mattermost-filestore-secret
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgBnYnb+nHmzzpvcJemkxrLgr7h1rJD+Orpe+sdAuMCeLy1RGg2Ls1zYrrVG4D/DwrBC0eSl+gKTnRaxomZ6qd3YAK4ez5Wbo2MsSkWXXg9thsHi4OqDE43sfKRy/btha/AZpFTiY3W4yME33g52MOCWSwHg1wA4cmUuhOfB5sif4FxM13sis1KPTfUkyjCph6knlNfYbBAPlkJDBjZyunUQlNAXb+34LswCFQF9oXQz5km88vqwRvP7OvBtrP2pW6FKWNesfurYlbL7YuwzK3HZL6I0GjV+mej0S1yWhdM0LiFkXDogLHks0Z7PZLI1XH5OfX4Irae60YP4612n6TDyxiMtwh9jlo31OvpS6W2jd9WdnxWiOr3IIOge5zr5PkPED993HO44nolZA17dNnPMy9wUxnoiMJpGSLHaFRXNr4z4K6FyPxW/8pmqPwbi5Jm+KujA9liRwc91KBQNGVsV21wVsfULwm1ewd+9zZAkDvnjDbJ9AvTqcSUyhFgaMhU9ppn81HLCl5hlX6pft71CeAGZAibkTqPRjj4GeBrul/G/A3jz44b0E4LVOg1Q/E6e9vtB3bakeuYlC2xCqfVJtnBGQRHIDEFZiB3aizDFhP/2CoKVhWhyyV1uBi8PoTc/3JUJ27902/11d42SnweMOGTTx8q4sLiaZiSPVNJ9lmt5VZ0gMxrdHRG8iul6c10Obp68IZmI0K/9daJBb8zk+FrA8g==
    secretkey: AgA8LxCIDk8D3llYJZ0JB/dh5VfTd/Ztj5MWdrdDaAr/eYEE7K4amKA52tOG57qvfacloHaV/RmiX6JnX1zSJ91d+39XaUKUM9btXrHdf0+utK4+IUFMZ1mVn2ByPTvcLob5/9lkzPZzqUh+YJlXMKqnQCnsGUmcsJs89pLHIVSz/1Oh4RIo2bFEQKxRj0gPAjng/H2+Py/Q6FhPqZUnGEDZdHJ983sw+XQDuBwhMKKtsZqsUiVN7zAyL8B0oTdAt2yCRrpW+9b0tm/CZeOMEdUkyIFpyRn4UL8YOSEOMkiBxlGTWHohcAJ/fTIrfa5v0sJMy9zZ5LBkMepqsamxXWeGb0KJ4K07jLzwo1wt546YhkJ5vSgPldfjm5kEE5Wcz4m994Weqw3PhCUDX6/3wonJ2GlMtfEDW3gHPAt7ujT4/zPF7BxD2c9kCMGPJ/l2DJJtxyyDm3fbmObJHw2xUOuNpsLatjGpcxq7m1i7qRRFlVSutW3YmcuHaxl02ZIDR7umSyWn2JBMpnc82jNaPuqIkzYEwcWTOJ4OFcHzEDOeHK47lwuKkKUocqthxmYPLhlqmzoTVgGjq7c+x0MkDoeuvbVkOZ2htfpZG0vch0LCVr9RikYKBU0MqvlWoc/P5obSybHB1qNjvKZTEtbnM7RrGmrg/Xgy/Imh8FXWxcznqkgOok7hs482AhakE2/5yWVJ7CbaY8pzcIV4lsTp9Kc/a5uFtqVEMnfA5JU2eO4SmJDrP0lNWgbj
  template:
    metadata:
      creationTimestamp: null
      name: mattermost-filestore-secret
      namespace: mattermost
