apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pgadmin4
  namespace: db
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
