apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        allowCrossNamespace: true
    gateway:
      namespacePolicy: All
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.home.lorenzolab.com`)
        entryPoints:
          - web
          - websecure
        tls:
          secretName: traefik-dashboard-certificate-secret
        middlewares:
          - name: auth-authentik@kubernetescrd
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      gitea-ssh:
        port: 55522
        expose:
          default: true
        exposedPort: 55522
