apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-certificate
  namespace: auth
spec:
  # Secret names are always required.
  secretName: auth-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - auth.lorenzolab.com
