apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets-repo
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://bitnami-labs.github.io/sealed-secrets
