apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-volume
  namespace: actual
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
