---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget
  namespace: actual
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd
