apiVersion: apps/v1
kind: Deployment
metadata:
  name: actualbudget
  namespace: actual
  labels:
    app.kubernetes.io/name: actualbudget
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: actualbudget
  template:
    metadata:
      labels:
        app.kubernetes.io/name: actualbudget
    spec:
      serviceAccountName: actualbudget
      containers:
        - name: actualbudget
          image: "actualbudget/actual-server:25.9.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: ACTUAL_PORT
              value: "5006"
            - name: ACTUAL_DATA_DIR
              value: /data
            - name: ACTUAL_SERVER_FILES
              value: /data/server-files
            - name: ACTUAL_USER_FILES
              value: /data/user-files
            - name: ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB
              value: "20"
            - name: ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB
              value: "50"
            - name: ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB
              value: "20"
            - name: ACTUAL_LOGIN_METHOD
              value: openid
            - name: ACTUAL_ALLOWED_LOGIN_METHODS
              value: openid
          envFrom:
            - secretRef:
                name: actualbudget-openid-secret
          ports:
            - name: http
              containerPort: 5006
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actualbudget
