apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: actualbudget-openid-secret
  namespace: actual
stringData:
  ACTUAL_MULTIUSER: ENC[AES256_GCM,data:TJ7XSg==,iv:s8quX9brU6RzpfnlZfxgeICLj9dHNm2cFguNyF5255Q=,tag:AbdFMzBkQ5jeAQqv5pJ1MA==,type:bool]
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:TC7t7uARZj+qnrvpP6EzN00ZbnCHaJYDBBGFGW8WYi7AxC6yES+RcQ==,iv:urEplUfZgHZh8msy3cTNsyKeqmSmj7zww31LfEqeiZw=,tag:kfy9TxybulbJN2WWj1GETA==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:6y6/yCXAXiqpEKKWtfZ9BD5YfcV0Zgy/1QlI/VLvlECqB3eb5zWZaQUyCMvE/X6hc41S4RU5qVbHchxs7SKZJAXRzFoCR32HMPrVDFFYhljXmF1pXPK1Dpg4V6gG+biMpS5h/EbWdSOYq9sxulL9pKtUWI1gcPYSYT7QEKfwyRw=,iv:ljcSwxFpbUpVSB1YpoqZ4nxyh8vNQKj2BkcV0zHHRZY=,tag:NdscHBy7Mmilu1voy+2TPA==,type:str]
  ACTUAL_OPENID_DISCOVERY_URL: ENC[AES256_GCM,data:/p+4QE62kpblhtwecMVOWKMNvjxVQKv36g8CFGGm1IOpCZ0tvwhgtsFYdkmMavgY+x6KK61IZNmiDoD+1DEOwnka4gg6Rj2JTiCbkNMXn86U+8NWnp3I,iv:OMdg6QoXct5Zy9SfrNNpvuc3msVigZH2Mg1aM2OkHug=,tag:kheLsFef6epiayN1Ix64iA==,type:str]
  ACTUAL_OPENID_ENFORCE: ENC[AES256_GCM,data:mO4RdA==,iv:D210njBr4AyeQ9GjBS241AKz+9kShNcU8WwLE8LhIKM=,tag:W2D9sVnWUEsxND/89/LC8Q==,type:bool]
  ACTUAL_OPENID_PROVIDER_NAME: ENC[AES256_GCM,data:Qvtn4ckpYehZ,iv:ldk/jifxzJ1y5CTxARD6a1pgIUhfthBf+FxEy6pIeTw=,tag:ADCWyphcoG2X0yNTk5jVJw==,type:str]
  ACTUAL_OPENID_SERVER_HOSTNAME: ENC[AES256_GCM,data:Ix9PvKYPAdq9mZXE4NegKPhDTjbjyc/iaPiqtyU=,iv:KAZwJLmgNC/PB5UC/kIBBAveEOI7UNDHL7xzDvyUCuw=,tag:WgvlHlT4BfM+H93FkpMs9A==,type:str]
sops:
  age:
    - recipient: age1dkx5fryjw78lpvu4fkk59k4ljl24a5cnsd5nj5sefh05p3xn9anszpqxuq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U0JxUlE0VDNibHRONjNw
        Snd0TXVEMmhEK2RURmZEN1BvREpwZUZuWEN3CkVtVzNYWk5NdlpFUmdtM2NkTHlj
        RFRZbFNHSWVJMStSQmRtM2lkM25FckUKLS0tIGludEZ0L3Y0cVZYdkVhcDVtQWln
        RmltOWNmSm4rOElsVTdZd0k3MjlldkUKkEtjhrA4VgimBC/SyFRoDB8P1K0CE/RN
        Vc2KDd92jemroLTaLHcZu5A73rKu4iWxFV5TWtn3WXkXRCaPLZ9Oyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-02T13:17:18Z"
  mac: ENC[AES256_GCM,data:6lShi2iftK/Q3BkoPyHFKbkzhSAMmhnK/ETsDodWVR9OSeOScBx9uK7kXU8BVdrXG0Y22oUPtlZanKPUYgGuC4QL114WiLgHftt8DhTzbyYX5RrHgf83VKhBIdlPByrJG0FzUPfB9mfFyVMLy6OK8vfbSZ5paaoyfyF+6LuRxTA=,iv:KbQpWPhGwdB6A0IPok9dqQTnCOSwIEdGB/RQJGPQsmc=,tag:Cp0MqU43+UfyGepYjeFv/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
