---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netbox
  namespace: &namespace netbox
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/netbox/netbox/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: cluster-issuer
      namespace: cert-manager
    - name: longhorn
      namespace: longhorn-system
  targetNamespace: *namespace
  timeout: 15m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
    - apiVersion: apps/v1
      kind: Deployment
      name: netbox
      namespace: netbox
    - apiVersion: apps/v1
      kind: Deployment
      name: netbox-worker
      namespace: netbox
