---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: db
spec:
  chart:
    spec:
      chart: pgadmin4
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pgadmin
      version: "1.50.0"
  interval: 1h
  values:
    strategy:
      type: Recreate
    existingSecret: pgadmin-secret
    persistentVolume:
      existingClaim: pgadmin-pvc
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: pgadmin.home.lorenzolab.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - pgadmin.home.lorenzolab.com
          secretName: pgadmin-certificate-secret
