---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mattermost-repo
  namespace: mattermost
spec:
  interval: 1h
  url: https://helm.mattermost.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mattermost-operator
  namespace: mattermost
spec:
  chart:
    spec:
      chart: mattermost-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mattermost-repo
      version: "1.0.3"
  interval: 1h
